# Generated by Django 4.2.9 on 2024-01-17 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_borrowed_by_remove_book_borrowed_on_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrowed_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
