# Generated by Django 4.2.9 on 2024-01-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_loan_borrowed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='rental_period',
            field=models.IntegerField(default=7),
        ),
    ]
