# Generated by Django 4.2.9 on 2024-01-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_author_alter_book_available_for_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='available_for_rent',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('novel', 'Novel'), ('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('biography', 'Biography'), ('autobiography', 'Autobiography'), ('history', 'History'), ('philosophy', 'Philosophy'), ('self_help', 'Self Help'), ('economics', 'Economics'), ('politics', 'Politics'), ('science', 'Science'), ('technology', 'Technology'), ('art', 'Art'), ('music', 'Music'), ('cooking', 'Cooking'), ('travel', 'Travel'), ('sports', 'Sports'), ('religion', 'Religion'), ('education', 'Education'), ('poetry', 'Poetry'), ('drama', 'Drama'), ('essay', 'Essay'), ('children', 'Children'), ('young_adult', 'Young Adult'), ('health', 'Health'), ('wellness', 'Wellness'), ('humor', 'Humor'), ('comics', 'Comics'), ('romance', 'Romance'), ('erotic', 'Erotic')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
