# Generated by Django 4.2.9 on 2024-01-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_author_alter_book_available_for_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_for_rent',
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
