# Generated by Django 4.2.7 on 2024-02-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('art', 'Art'), ('autobiography', 'Autobiography'), ('biography', 'Biography'), ('children', 'Children'), ('comics', 'Comics'), ('cooking', 'Cooking'), ('drama', 'Drama'), ('economics', 'Economics'), ('education', 'Education'), ('erotic', 'Erotic'), ('essay', 'Essay'), ('fantasy', 'Fantasy'), ('fiction', 'Fiction'), ('health', 'Health'), ('history', 'History'), ('horror', 'Horror'), ('humor', 'Humor'), ('music', 'Music'), ('mystery', 'Mystery'), ('non_fiction', 'Non-Fiction'), ('novel', 'Novel'), ('philosophy', 'Philosophy'), ('poetry', 'Poetry'), ('politics', 'Politics'), ('religion', 'Religion'), ('romance', 'Romance'), ('science', 'Science'), ('science_fiction', 'Science Fiction'), ('self_help', 'Self Help'), ('sports', 'Sports'), ('technology', 'Technology'), ('thriller', 'Thriller'), ('travel', 'Travel'), ('wellness', 'Wellness'), ('young_adult', 'Young Adult')], max_length=50, null=True),
        ),
    ]
